### ISSUE TITLE
prefuse.org seems to be sold

### ISSUE THREAD

**Issue by koppor** [prefuse/Prefuse#37]
Now:

![grafik](https://user-images.githubusercontent.com/1366654/78408503-a0a15e00-7607-11ea-90c7-471a9716cd9a.png)

Back then:

![grafik](https://user-images.githubusercontent.com/1366654/78408527-b6af1e80-7607-11ea-83c6-6ec195cf08d8.png)

(via https://web.archive.org/web/20180308141540/http://prefuse.org/)

Suggestion: Remove the link from the repository information

![grafik](https://user-images.githubusercontent.com/1366654/78408556-cb8bb200-7607-11ea-9872-a841a9fa13be.png)

**Comment by alex-rind** [comment]
👍  but only an owner can remove the link 
Alexander

**Comment by apjanke** [comment]
Don't suppose anyone has an archive of the source to prefuse.org? It had the User Manual and other documentation that seem useful.

**Comment by apjanke** [comment]
Hey look, there's what appears to be a live copy of the site over at <http://kneecap.ist.berkeley.edu/>. I wonder who's running that?

**Comment by wjwillett** [comment]
I believe prefuse.org was actually just an alias for that Berkeley site. However, none of the original developers are still at Berkeley (last person directly associated with Prefuse left in 2013 or 2014), so not sure how long the documentation there will remain online or who still has access to that server (I don't believe I do). In the meantime I've updated the link to point to the Berkeley server.

**Comment by apjanke** [comment]
I sent a request to itcsshelp@berkeley.edu asking if they could track down the current site owner.

I also scraped a mirror of kneecap using HTTrack so the content (at least as presented in HTML; I dunno if the site is built from some other format) isn't lost if the server falls offline.

[kneecap.ist.berkeley.edu-scrape-2020-05-31.zip](https://github.com/prefuse/Prefuse/files/4708597/kneecap.ist.berkeley.edu-scrape-2020-05-31.zip)
